SKILL_NAMES: dict[str, str] = {
    "acrobatics": "体操",
    "animal_handling": "驯兽",
    "arcana": "奥秘",
    "athletics": "运动",
    "deception": "欺瞒",
    "history": "历史",
    "insight": "洞悉",
    "intimidation": "威吓",
    "investigation": "调查",
    "medicine": "医药",
    "nature": "自然",
    "perception": "察觉",
    "performance": "表演",
    "persuasion": "游说",
    "religion": "宗教",
    "sleight_of_hand": "巧手",
    "stealth": "隐匿",
    "survival": "求生",
}

SKILL_ATTRIBUTES: dict[str, str] = {
    "acrobatics": "dex",
    "animal_handling": "wis",
    "arcana": "int",
    "athletics": "str",
    "deception": "cha",
    "history": "int",
    "insight": "wis",
    "intimidation": "cha",
    "investigation": "int",
    "medicine": "wis",
    "nature": "int",
    "perception": "wis",
    "performance": "cha",
    "persuasion": "cha",
    "religion": "int",
    "sleight_of_hand": "dex",
    "stealth": "dex",
    "survival": "wis",
}
