name: Deploy to dnd5ebuilder-beta

on:
  push:
    branches: [refactor]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build hook
        run: curl -X POST "https://api.netlify.com/build_hooks/6a37a482c994ade5e02f04b8"
