name: Deploy to dnd5ebuilder-beta

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build hook
        run: curl -X POST "https://api.netlify.com/build_hooks/6a37a39ee467cdc9adf89fb8"
